# -*- coding: utf-8 -*-
"""meat_consumption_ranking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M9BCb5FeUn31iU5Bxkl1uL9dBrjdOWvH
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import scipy as sp
import scipy.stats

# %matplotlib inline

datapath = './per-capita-meat-consumption-by-type-kilograms-per-year.csv'
data = pd.read_csv(datapath)

print(data.shape)
print("--------------------------------------------------------------------------------")
print(data.columns)
print("--------------------------------------------------------------------------------")
print(data.info())

data

data.drop('Code', axis=1, inplace=True)

c = data['Year'] >= 1991
data_eda = data[c]

data_eda.info()

data_eda[data_eda['Pigmeat (kilograms per year)'].isnull()].Entity.unique()

"""> 이슬람 국가로 돼지고기 소비량 0으로 결측치 채워줌"""

data_fill = data_eda.fillna(0)

data_fill.rename(columns={'Mutton and Goat (kilograms per year)':'Mutton and Goat', 'Other meats (kilograms per person)':'Other meats', 'Poultry (kilograms per year)':'Poultry', 'Pigmeat (kilograms per year)':'Pigmeat', 'Beef and bufallo (kilograms per year)':'Beef and bufallo'}, inplace=True)

data_fill['Total Consumption(kg/year)'] = data_fill['Mutton and Goat'] + data_fill['Beef and bufallo'] + data_fill['Other meats'] + data_fill['Pigmeat'] + data_fill['Poultry']

data_fill

set_Country2 = ['China', 'United States', 'Russia', 'Brazil',
       'Japan', 'Germany', 'Canada', 'Mexico', 'Australia', 'South Africa',
       'United Kingdom', 'Argentina', 'Italy', 'France', 'Poland', 'Spain',
       'Ukraine', 'Netherlands', 'South Korea']

# 온실가스 배출량 상위 20개국과 한국 포함

data_set_country = data_fill.pivot('Entity', 'Year', 'Total Consumption(kg/year)').loc[set_Country2].drop(1991, axis=1)

data_set_country

data_set_country['ratio'] = ((data_set_country[2017] - data_set_country[1992])/data_set_country[1992])*100

data_set_country

data_set_country['increase_rank'] = data_set_country['ratio'].rank(method='dense', ascending=False)

data_set_country

increase_data = data_set_country[[1992, 2017, 'ratio', 'increase_rank']]

increase_rank_data = increase_data.sort_values(by='ratio', ascending=False)

increase_rank=increase_rank_data.round(0).reset_index().rename(columns={'Entity':'Country', 'ratio':'Change(%)', 'increase_rank':'Ranking'})

increase_rank.to_csv('rateofchange.csv')

increase_rank

rank = data_set_country.rank(method='dense', ascending=False)

rank_df = pd.DataFrame(rank)

col_in = data_set_country[['ratio', 'increase_rank']]

rank_df_ratioin = pd.concat([rank_df, col_in], axis=1)

rank_df_ratioin

rank_consumption = rank_df_ratioin.sort_values(by=1992)

rank_consumption

ranking = rank_consumption[[1992, 1998, 2004, 2010, 2016]]

ranking.to_csv('meat_consumption_ranking.csv')

ranking

z = pd.DataFrame(ranking.stack()).reset_index()
z.columns = ['country','x','y']


result = []
for i in z.country.unique():
    records = {}
    
    records['data'] = z.query(f'country=="{i}"').loc[:,['x','y']].to_dict('records')
    records['id'] = i
        
    result.append(records)

result